repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args: [--fix, backend]
        pass_filenames: false
        files: ^backend/.*\.py$

      - id: ruff-format
        args: [backend]
        pass_filenames: false
        files: ^backend/.*\.py$

  - repo: local
    hooks:
      - id: frontend-eslint
        name: frontend-eslint
        entry: npm --prefix frontend run lint
        language: system
        pass_filenames: false
        files: ^frontend/.*\.(js|jsx)$

      - id: frontend-prettier
        name: frontend-prettier
        entry: npm --prefix frontend run format
        language: system
        pass_filenames: false
        files: ^frontend/.*\.(js|jsx|css|html)$
